### PR TITLE
No -> mo conversion

### PR DESCRIPTION
**Pull request by ryanfox**
change novel to movie

### CODE REVIEW

**Comment by ryanfox** [comment]
Ugh, github UI messed me up. Disregard this.

**Comment by hugovk** [comment]
Fun idea!

* https://namogenmo.github.io/
* https://github.com/NaMoGenMo/2022

We could list this and some other spin-offs on https://nanogenmo.github.io/, there's also https://github.com/napogenmo and https://github.com/cpressey/NaOpGenMo :)

**Comment by ryanfox** [comment]
That would be cool. A collection of Gen Mos. (GenMoCo?)

Didn't mean to change this repo 😅

**Comment by hugovk** [comment]
https://github.com/NaNoGenMo/nanogenmo.github.io/pull/10 :)

**Pull request closed without merging**
